spring:
  application:
    name: jampot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: MySQL8

  profiles:
    include:
      - rds
      - oauth2

  jwt:
    secret: ${JWT_SECRET}


cookie:
  secure: ${COOKIE_SECURE}

swagger:
  authorizationUrl: ${SWAGGER_AUTHORIZATION_URL}
  tokenUrl: ${SWAGGER_TOKEN_URL}

