cloud:
  aws:
    credentials:
      access-key: "${S3_ACCESS_KEY}"
      secret-key: "${S3_SECRET_KEY}"

spring:
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB