# ?? MySQL ??
spring.datasource.url=${LOCAL_MYSQL_URL}
spring.datasource.username=${LOCAL_MYSQL_USERNAME}
spring.datasource.password=${LOCAL_MYSQL_PASSWORD}

# ?? MongoDB ??
spring.data.mongodb.uri=${LOCAL_MONGODB_URI}

# ?? Redis ??
spring.redis.host=${LOCAL_REDIS_HOST}
spring.redis.port=${LOCAL_REDIS_PORT}