spring.application.name=JamPot

server.port=8085

# ?? ?? (??/?? ?? ??)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ?? ?? ??? ?? ???? (?? ? 'none'?? ??)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect



#?? ????? ??? ??
spring.profiles.active=local




