spring:
  application:
    name: jampot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect


  profiles:
    include:
      - rds
      - oauth2
      - s3

  jwt:
    secret: "${JWT_SECRET}"


cookie:
  secure: "${COOKIE_SECURE}"
  samesite: "${COOKIE_SAMESITE}"
  login-guest-redirectUrl: "${COOKIE_LOGIN_GUEST_REDIRECT_URL}"
  login-user-redirectUrl: "${COOKIE_LOGIN_USER_REDIRECT_URL}"

swagger:
  authorizationUrl: "${SWAGGER_AUTHORIZATION_URL}"
  tokenUrl: "${SWAGGER_TOKEN_URL}"

logging:
  level:
    org.springframework.web: TRACE
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.security.oauth2.core: DEBUG
    org.springframework.security.web.authentication: DEBUG